# Generated by Django 4.1.5 on 2023-02-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cart_payment_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='payment_ref_id',
        ),
    ]
